[package]
name = "ND-Lang"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
lazy_static = "1.4.0"
once_cell = "1.17.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.17.1"
